# Generated by Django 4.0.6 on 2023-07-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='optionID',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='answer',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='randoms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.option'),
        ),
    ]
