# Generated by Django 4.0.6 on 2023-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_option_optionid_alter_details_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
