# Generated by Django 4.0.6 on 2023-07-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_details_created_details_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
