# Generated by Django 4.0.6 on 2023-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_details_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='optionID',
            field=models.IntegerField(null=True),
        ),
    ]
