# Generated by Django 4.0.6 on 2023-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_randoms_detail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
