# Generated by Django 4.0.6 on 2023-07-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_options_detail_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='option',
            new_name='uno',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='answer',
        ),
    ]
