# Generated by Django 4.0.6 on 2023-07-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_option_detail_uno_remove_detail_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='uno',
        ),
        migrations.AddField(
            model_name='detail',
            name='option',
            field=models.ManyToManyField(to='main.option'),
        ),
        migrations.AddField(
            model_name='detail',
            name='optionID',
            field=models.IntegerField(null=True),
        ),
    ]
