# Generated by Django 4.2.3 on 2023-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_optionid_detail_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
