# Generated by Django 4.2.3 on 2023-08-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_list_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='optionID',
        ),
    ]
