# Generated by Django 4.2.3 on 2023-08-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_option_optionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='option',
            new_name='options',
        ),
    ]
