# Generated by Django 4.0.6 on 2023-08-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_option_detail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
