# Generated by Django 4.0.6 on 2023-08-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_cou'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cou',
        ),
    ]
